### ISSUE TITLE
Does Coco API has any GPU version?

### ISSUE THREAD

**Issue by BestSonny** [pdollar/coco#15]
@pdollar When comes to IoU with many boxes or polys, it seems be very slow. Is there a GPU version? If not, any reference?

**Comment by pdollar** [comment]
There is no GPU implementation and no plans for one, sorry. However, I'm a bit surprised you say the IoU computation is slow. It's actually quite optimized c code, and for masks we actually have quite an efficient implementation that is dependent on the perimeter of the mask instead of the area (see http://mscoco.org/dataset/#download, section 3). Compared to a naive implementation it is actually 100x faster or so, and it is fast enough that in the evaluation code the iou computation is not a bottleneck..  Of course if you are comparing say 1000 to 1000 masks (10^6 iou computations, it will take some time). I just tested this case and it takes about .5s on my Mac for masks, and .02s for boxes. Whether that is fast or slow is subjective, but those are the speeds you should be getting. Note that if you are doing NMS or something, you probably shouldn't be doing brute force NMS on masks directly for 1000s of masks (e.g., you might want to do NMS on boxes first then for surviving ones do NMS on masks). You can also see the edgeBoxes nms c implementation (https://github.com/pdollar/edges/blob/master/private/edgeBoxesMex.cpp, line 399-420) which avoids doing the whole n^2 IoU computation and is closer to nlogn.

**Comment by BestSonny** [comment]
@pdollar  Thank you a lot. IoU computation on boxes is quite efficient. I didn't notice the detail before. I figure out the reason why my code is very slow is caused by the scale. I was trying to upsampled all points which you already did it for us in [here](https://github.com/pdollar/coco/blob/master/common/maskApi.c#L141#L144). Again, thank you for the excellent code.
```
Poly1 = {}
Poly2 = {}
for i=1,20000 do
  table.insert(Poly1,torch.DoubleTensor({1, 1, 5, 1, 19, 31, 4, 6}):mul(100))
end
for i=1,10 do
  table.insert(Poly2,torch.DoubleTensor({1, 1, 20, 1, 20, 20, 1, 20}):mul(100))
end
```

**Comment by pdollar** [comment]
Great, glad it's working better for you now :)
