### ISSUE TITLE
urls no longer work

### ISSUE THREAD

**Issue by aquiire** [pdollar/coco#73]
The urls of the form `http://mscoco..../images/imgId` no longer work.
The jupyter notebooks should also be updated.

**Comment by aquiire** [comment]
The new annotations are updated.

**Comment by aquiire** [comment]
But jupyter notebook is not.

**Comment by tylin** [comment]
Thanks for reporting this. The coco_url in demo was updated.
https://github.com/pdollar/coco/blob/master/PythonAPI/pycocoDemo.ipynb

**Comment by wlw208dzy** [comment]
I would like to participate in the det challenge of COCO-2017. But now I could not access the address of **http://cocodataset.org/#download**. Would you mind sending me the download address of "image_info" for 'test_2017'?@

**Comment by nightrome** [comment]
Could you elaborate what exactly doesn't work? I can download this file:
http://images.cocodataset.org/annotations/image_info_test2017.zip

On Sep 23, 2017 04:42, "wlw208dzy" <notifications@github.com> wrote:

I would like to participate in the det challenge of COCO-2017. But now I
could not access the address of *http://cocodataset.org/#download
<http://cocodataset.org/#download>*. Would you mind sending me the download
address of "image_info" for 'test_2017'?@

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cocodataset/cocoapi/issues/73#issuecomment-331605394>,
or mute the thread

**Comment by wlw208dzy** [comment]
Thanks. The link is OK.
